Version: '3'

services:

  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        ## ------------------------------------------------------ ##
        ###  available profiles: local
        ###  available override/extend profiles: dockermq, mock
        ## ------------------------------------------------------ ##
        springprofileactive: local, dockermq, mock
    depends_on:
      - ibm.mq
    ports:
      - '8080:8080'
    links:
      - ibm.mq1
      - ibm.mq2
  ibm.mq1:
    image: ibmcom/mq
    environment:
      LICENSE: 'accept'
      MQ_QMGR_NAME: 'QM1'
    ports:
      - '1414:1414'
      - '9443:9443'
  ibm.mq2:
    image: ibmcom/mq
    environment:
      LICENSE: 'accept'
      MQ_QMGR_NAME: 'QM1'
    ports:
      - '1415:1415'
      - '9444:9444'