# Application
spring:
  application:
    name: demo
  queues:
    queue1:
      mockit: false
      disabled: false
      app-description: Queue1
      app-name: Queue1 dockermq
      host: ibm.mq1
      password: passw0rd
      username: admin
      channel: DEV.ADMIN.SVRCONN
      port: 1414
      queue-manager: QM1
      listen-topic: DEV.QUEUE.1
      publish-topic: DEV.QUEUE.2
      concurrent: 1
      pubSub: false
    queue2:
      mockit: false
      disabled: false
      app-description: Queue2
      app-name: Queue2 dockermq
      host: ibm.mq2
      password: passw0rd
      username: admin
      channel: DEV.ADMIN.SVRCONN
      port: 1414
      queue-manager: QM1
      listen-topic: DEV.QUEUE.2
      publish-topic: DEV.QUEUE.3
      concurrent: 1
      pubSub: false


