spring:
  queues:
    queue1:
      app-description: Queue1
      app-name: Queue1 dockermq
      host: ibm.mq1
      password: passw0rd
      username: admin
    queue2:
      app-description: Queue2
      app-name: Queue2 dockermq
      host: ibm.mq2
      password: passw0rd
      username: admin
