# Application
spring:
  application:
    name: demo
  queues:
    queue1:
      mockit: false
      disabled: false
      app-description: queue1
      app-name: queue1 local
      channel: DEV.ADMIN.SVRCONN
      host: localhost
      password: passw0rd
      username: admin
      port: 1414
      queue-manager: QM1
      listen-topic: DEV.QUEUE.1
      publish-topic: DEV.QUEUE.2
      concurrent: 3
      pubSub: false
    queue2:
      mockit: false
      disabled: false
      app-description: queue2
      app-name: queue2 local
      channel: DEV.ADMIN.SVRCONN
      host: localhost
      password: passw0rd
      username: admin
      port: 1414
      queue-manager: QM1
      listen-topic: DEV.QUEUE.2
      publish-topic: DEV.QUEUE.3
      concurrent: 3
      pubSub: false
